Hide console on Windows with -ldflags -H=windowsgui

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -63,7 +63,11 @@ jobs:
           GOARCH: ${{ matrix.goarch }}
           CGO_ENABLED: 1
         run: |
-          go build -v -o csv-to-excel-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }} main.go || (echo "Build failed" && exit 1)
+          if [ "${{ matrix.goos }}" = "windows" ]; then
+            go build -v -ldflags "-H=windowsgui" -o csv-to-excel-${{ matrix.goos }}-${{ matrix.goarch }}.exe main.go || (echo "Build failed" && exit 1)
+          else
+            go build -v -o csv-to-excel-${{ matrix.goos }}-${{ matrix.goarch }} main.go || (echo "Build failed" && exit 1)
+          fi
 
       - name: Upload artifact
         uses: actions/upload-artifact@v4
